const roles = [
  // Tech/IT
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "UI/UX Designer",
  "Product Manager",
  "System Administrator",
  "Network Engineer",
  "Cybersecurity Specialist",
  "Cloud Architect",
  "Database Administrator",
  "QA Engineer",
  "Mobile App Developer",
  "Game Developer",
  "AI Engineer",
  "Blockchain Developer",
  "React Developer",
  "Vue Developer",
  "Angular Developer",
  "Node.js Developer",
  "Python Developer",
  "Java Developer",
  "C++ Developer",
  "PHP Developer",

  // Business/Finance
  "Business Analyst",
  "Financial Analyst",
  "Marketing Manager",
  "Sales Representative",
  "Account Manager",
  "Project Manager",
  "Operations Manager",
  "Business Development Manager",
  "Investment Banker",
  "Financial Advisor",
  "Risk Analyst",
  "Accountant",
  "Auditor",
  "Controller",
  "CFO",
  "CEO",
  "COO",
  "CTO",
  "Marketing Specialist",
  "Digital Marketing Manager",
  "SEO Specialist",
  "PPC Specialist",
  "Content Marketing Manager",
  "Brand Manager",

  // Healthcare
  "Doctor",
  "Nurse",
  "Surgeon",
  "Dentist",
  "Pharmacist",
  "Physical Therapist",
  "Medical Assistant",
  "Radiologist",
  "Cardiologist",
  "Pediatrician",
  "Psychiatrist",
  "Psychologist",
  "Medical Technician",
  "Healthcare Administrator",
  "Veterinarian",
  "Nurse Practitioner",
  "Physician Assistant",
  "Medical Researcher",

  // Education
  "Teacher",
  "Professor",
  "Principal",
  "Education Administrator",
  "Curriculum Designer",
  "School Counselor",
  "Librarian",
  "Research Scientist",
  "Academic Advisor",
  "Tutor",
  "Training Specialist",
  "Instructional Designer",
  "Education Consultant",

  // Creative/Media
  "Graphic Designer",
  "Web Designer",
  "Content Writer",
  "Copywriter",
  "Video Editor",
  "Photographer",
  "Social Media Manager",
  "Brand Manager",
  "Creative Director",
  "Art Director",
  "Animator",
  "Sound Engineer",
  "Music Producer",
  "Journalist",
  "Editor",
  "Public Relations Specialist",
  "Content Creator",
  "Blogger",
  "Motion Graphics Designer",
  "Illustrator",
  "Game Designer",

  // Legal
  "Lawyer",
  "Attorney",
  "Legal Assistant",
  "Paralegal",
  "Judge",
  "Legal Advisor",
  "Compliance Officer",
  "Contract Manager",
  "Patent Attorney",
  "Corporate Lawyer",
  "Criminal Defense Attorney",
  "Immigration Lawyer",
  "Tax Attorney",

  // Engineering
  "Mechanical Engineer",
  "Civil Engineer",
  "Electrical Engineer",
  "Chemical Engineer",
  "Aerospace Engineer",
  "Environmental Engineer",
  "Biomedical Engineer",
  "Industrial Engineer",
  "Structural Engineer",
  "Petroleum Engineer",
  "Nuclear Engineer",
  "Materials Engineer",
  "Automotive Engineer",

  // Sales/Customer Service
  "Sales Manager",
  "Sales Executive",
  "Customer Service Representative",
  "Customer Success Manager",
  "Technical Support Specialist",
  "Call Center Agent",
  "Retail Manager",
  "Store Manager",
  "Cashier",
  "Sales Associate",
  "Inside Sales Representative",
  "Outside Sales Representative",
  "Account Executive",

  // Human Resources
  "HR Manager",
  "HR Generalist",
  "Recruiter",
  "Talent Acquisition Specialist",
  "Compensation Analyst",
  "Training Coordinator",
  "Employee Relations Specialist",
  "Benefits Administrator",
  "HRIS Administrator",
  "HR Business Partner",

  // Manufacturing/Operations
  "Production Manager",
  "Quality Control Inspector",
  "Manufacturing Engineer",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Warehouse Manager",
  "Operations Analyst",
  "Process Improvement Specialist",
  "Plant Manager",
  "Inventory Manager",
  "Procurement Specialist",
  "Distribution Manager",

  // Consulting
  "Management Consultant",
  "Strategy Consultant",
  "IT Consultant",
  "Business Consultant",
  "Financial Consultant",
  "Marketing Consultant",
  "Operations Consultant",
  "Technology Consultant",
  "HR Consultant",
  "Change Management Consultant",

  // Other Popular Roles
  "Administrative Assistant",
  "Executive Assistant",
  "Office Manager",
  "Receptionist",
  "Data Entry Clerk",
  "Research Assistant",
  "Intern",
  "Freelancer",
  "Contractor",
  "Consultant",
  "Advisor",
  "Coordinator",
  "Specialist",
  "Analyst",
  "Manager",
  "Director",
  "Vice President",
  "Senior Manager",
  "Team Lead",
  "Supervisor",
  "Virtual Assistant",
  "Event Coordinator",
  "Travel Agent",
  "Real Estate Agent",
];

export default roles;
